# making the ci with docker also

name: CI With Docker/Docker-Compose

on:
  push:
    branches: ["main"]

jobs:
  docker-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: building images with docker compose
        run: docker compose build

      - name: running the docker compose
        run: docker compose up -d

      - name: waiting for db because it takes time
        run: sleep 20

      - name: running test for frontend
        run: docker compose exec -T client npm test

      - name: running test for backend
        run: docker compose exec -T server npm test

      - name: taking down the compose
        if: always()
        run: docker compose down
